import apiClient from './client';

export const productionApi = {
  listTemplates: () => apiClient.get('/api/production/templates'),
  getTemplate: (id) => apiClient.get(`/api/production/templates/${id}`),
  createTemplate: (payload) => apiClient.post('/api/production/templates', payload),
  updateTemplate: (id, payload) => apiClient.put(`/api/production/templates/${id}`, payload),
  listOrders: () => apiClient.get('/api/production/orders'),
  createOrder: (payload) => apiClient.post('/api/production/orders', payload),
  updateOrder: (id, payload) => apiClient.put(`/api/production/orders/${id}`, payload),
  createBatch: (payload) => apiClient.post('/api/production/batches', payload),
  listBatches: (status, templateId, q) => apiClient.get('/api/production/batches', { params: { status, templateId, q } }),
  getBatch: (id) => apiClient.get(`/api/production/batches/${id}`),
  startBatch: (id) => apiClient.post(`/api/production/batches/${id}/start`),
  issueBatch: (id, payload) => apiClient.post(`/api/production/batches/${id}/issue`, payload),
  completeStep: (id, stepNo, payload) => apiClient.post(`/api/production/batches/${id}/step/${stepNo}/complete`, payload),
  produceOutput: (id, payload) => apiClient.post(`/api/production/batches/${id}/produce`, payload),
  completeBatch: (id) => apiClient.post(`/api/production/batches/${id}/complete`),
  listWipOutputs: (batchId) => apiClient.get(`/api/production/batches/${batchId}/wip-outputs`),
  getCostSummary: (batchId) => apiClient.get(`/api/production/batches/${batchId}/cost-summary`),
  listWipBalances: () => apiClient.get('/api/production/wip/balances'),
  listBatchRuns: (batchId) => apiClient.get(`/api/production/batches/${batchId}/runs`),
  createRun: (batchId, payload) => apiClient.post(`/api/production/batches/${batchId}/runs`, payload),
  updateRun: (runId, payload) => apiClient.put(`/api/production/runs/${runId}`, payload),
  getRun: (runId) => apiClient.get(`/api/production/runs/${runId}`),
  postRun: (runId) => apiClient.post(`/api/production/runs/${runId}/post`),
  getRunCostSummary: (runId) => apiClient.get(`/api/production/runs/${runId}/cost-summary`),
  listBatchWip: (batchId) => apiClient.get(`/api/production/batches/${batchId}/wip`),
  searchWip: (search) => apiClient.get('/api/wip', { params: { search } })
};
