ALTER TABLE debit_note_lines
  ADD COLUMN IF NOT EXISTS rule_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS description VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS base_value DECIMAL(14,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rate DECIMAL(14,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount DECIMAL(14,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS remarks VARCHAR(255) NULL;
