CREATE TABLE sales_attendance (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  attendance_date DATE NOT NULL,
  check_in_time TIME,
  check_out_time TIME,
  check_in_location VARCHAR(255),
  check_out_location VARCHAR(255),
  check_in_lat DOUBLE,
  check_in_lng DOUBLE,
  check_out_lat DOUBLE,
  check_out_lng DOUBLE,
  travel_km DECIMAL(10, 2),
  rate_per_km DECIMAL(10, 2),
  ta_amount DECIMAL(12, 2),
  da_amount DECIMAL(12, 2),
  total_amount DECIMAL(12, 2),
  remarks VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR(255) NOT NULL,
  CONSTRAINT fk_sales_attendance_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_sales_attendance_user FOREIGN KEY (user_id) REFERENCES users(id)
);
